#!/usr/bin/php -q
<?php

/**
 * Copyright 2015 Rafal Zajac <rzajac@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

// Require composer autoload file
foreach (
    [
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../vendor/autoload.php',
        __DIR__ . '/vendor/autoload.php'
    ] as $file) {
    if (file_exists($file)) {
        /** @noinspection PhpIncludeInspection */
        require $file;
        break;
    }
}

use Kicaj\SchemaDump\Cli;
use Kicaj\SchemaDump\SchemaDump;

$cliOptions = getopt(Cli::getCliShortOptions(), Cli::getCliLongOptions());

$cli = Cli::make();

if (!$cli->setOptions($cliOptions)) {
    echo $cli->getError()->getMessage();
    exit(1);
}

$exporter = SchemaDump::make($cli->getDbConfig())
                      ->addIfNotExists($cli->isAddIfNotExists());

if ($exporter->hasError()) {
    echo $exporter->getError()->getMessage() . "\n";
    exit(1);
}

$content = $exporter->getCreateStatements($cli->getFormat());
$outputFile = $cli->getOutputFile();

if ($outputFile) {
    file_put_contents($outputFile, $content);
    echo "schema for exported\n";
} else {
    echo $content;
}

